apiVersion: rabbit-stalker.prosimcorp.com/v1alpha1
kind: WorkloadAction
metadata:
  labels:
    app.kubernetes.io/name: workloadaction
    app.kubernetes.io/instance: workloadaction-sample
    app.kubernetes.io/part-of: rabbit-stalker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rabbit-stalker
  name: workloadaction-sample
spec:
  synchronization:
    time: 10s

  # Configuration
  rabbitConnection:
    url: "https://your-server.rmq.cloudamqp.com"
    queue: "your-queue-here"
    useRegex: false

    # (Optional) Vhost can be set (or not) when searching queues using regex patterns,
    # (Mandatory) Vhost is required for searches based on exact queue names.
    vhost: "shared"

    # (Optional) Credentials to authenticate against endpoint.
    # If set, both are required
    credentials:
      username:
        secretRef:
          name: testing-secret
          key: RABBITMQ_USERNAME

          # (Optional) Getting credentials from other namespace is possible too
          # When namespace is not defined, the same where this WorkloadAction CR is running will be used
          namespace: default
      password:
        secretRef:
          name: testing-secret
          key: RABBITMQ_PASSWORD

  # (Optional) Additional sources to get information from.
  # This sources can be used on condition.value
  additionalSources:
    - apiVersion: apps/v1
      kind: Deployment
      name: testing-workload
      namespace: default

  # Condition under the action is executed.
  condition:
    # The 'key' field admits dot notation, and it's covered by gjson
    # Ref: https://github.com/tidwall/gjson
    key: |-
      consumer_details.#(channel_details.node==rabbit@fancy-monk-sample-01).channel_details.node

    # Additional sources from 'additionalSources' field can be used here to craft complex values using the pattern:
    # [index]{{ gjson }}
    value: |-
      [0]{{ metadata.annotations.node }}

  # Action to do with the workload when the condition is met
  action: "restart"

  # The workload affected by the action
  workloadRef:
    
    # It's possible to use core resources from Kubernetes
    #apiVersion: apps/v1
    #kind: Deployment
    #name: testing-workload
    #namespace: default

    # Some custom resources can be used too
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: testing-workload-argo-rollout
    namespace: default

